# Generated by Django 5.2.9 on 2025-12-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('C', 'Completed'), ('R', 'Reading'), ('W', 'Want to Read')], default='W', max_length=1),
        ),
    ]
